import requests
import re
import textwrap as tw
import click
import json

LOADER_VERSION = '0.14.21'

@click.command()
@click.argument('minecraft-version')
@click.option('--mod-version', default=None, help='The Mod Version, if not specified reads version from last gradle.properties')
def update(minecraft_version, mod_version):
    minecraft_version = re.sub(r'^(\d+\.\d+)\.0(-.*)?$', r'\1\2', minecraft_version)
    if mod_version is None:
        with open('gradle.properties', 'r') as f:
            match = next(re.finditer(r'mod_version\s*=\s*(.*)', f.read()), None)
            assert match is not None, 'Could not find mod_version in gradle.properties'
            mod_version = match.groups()[0]

    versions = {}
    for dep in ['fabric-api', 'modmenu', 'cloth-config']:
        response = requests.get(f'https://api.modrinth.com/v2/project/{dep}/version').json()
        vs = []
        for v in response:
            if 'fabric' in v.get('loaders', []) and minecraft_version in v.get('game_versions', []):
                vs.append(v)

        assert vs, f'No {dep} version found for Minecraft version {minecraft_version}'

        def version_key(v):
            version_number = v['version_number']
            prerelease = v["version_type"] != "release"
            match = re.match(r'(\d+)\.(\d+)\.(\d+)', version_number)
            assert match is not None, f'Invalid version number: {version_number}'

            major, minor, patch = map(int, match.groups())

            return (major, not prerelease, -minor, -patch)

        versions[dep] = max(vs, key=version_key)['version_number']
        if dep == 'cloth-config':
            versions[dep] = versions[dep].split('+')[0]

    gradle_properties = tw.dedent(f'''
        # This file was automatically generated by updater.py

        org.gradle.jvmargs=-Xmx1G

        # Mod Properties
        mod_version={mod_version}
        mod_group_id=net.micha4w
        mod_id=Soft_ToggleSneak

        minecraft_version={minecraft_version}

        # Fabric Properties # TODO: also check https://meta.fabricmc.net/v2/versions/loader/{minecraft_version}
        loader_version={LOADER_VERSION}

        # Dependencies
        fabric_api_version={versions['fabric-api']}
        cloth_config_version={versions['cloth-config']}
        modmenu_version={versions['modmenu']}
    ''')[1:]

    with open('gradle.properties', 'w') as f:
        f.write(gradle_properties)

    with open('src/main/resources/fabric.mod.json', 'r') as f:
        fabric_mod_json = json.load(f)

    fabric_mod_json["depends"] = {
        "fabricloader": f">={LOADER_VERSION}",
        "fabric-api": f">={versions['fabric-api']}",
        "java": ">=25",
        "minecraft": f">={minecraft_version}"
    }

    fabric_mod_json["suggests"] = {
        "cloth-config2": f">={versions['cloth-config']}",
        "modmenu": f">={versions['modmenu']}"
    }

    with open('src/main/resources/fabric.mod.json', 'w') as f:
        json.dump(fabric_mod_json, f, indent=2)


if __name__ == '__main__':
    update()
